version: "3.1"
services:
  postgres:
    container_name: postgres_container
    restart: unless-stopped
    image: test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # PGDATA: ./data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped