version: "3.1"
services:
  postgres:
    container_name: foodService_postgres
    restart: unless-stopped
    build: db/.
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # PGDATA: ./data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    container_name: foodService_api
    restart: unless-stopped
    build: .
    env_file: .env
    ports:
      - "8000:8000"