version: "3.1"
services:
  postgres:
    container_name: foodService_postgres
    restart: unless-stopped
    image: adrianvillanueva997/foodservice_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # PGDATA: ./data/postgres
    ports:
      - "5432"
    restart: unless-stopped
  api:
    container_name: foodService_api
    restart: unless-stopped
    image: adrianvillanueva997/foodservice_api
    env_file: .env
    depends_on: 
      - postgres
    ports:
      - "8000:8000"