name: Build API

on:
  push:
    branches:
      - master

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          apk add --no-cache make
          make docker-lint

  build-docker:
    runs-on: ubuntu-latest
    needs: [docker-lint]
    steps:
      - name: Set up CD
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v1.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Docker login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./db
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            adrianvillanueva997/foodservice_db:${{ github.sha }}
            adrianvillanueva997/foodservice_db:latest
